# Generated by Django 5.2.17 on 2026-09-03 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_m3_durable_execution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_ERRORS', 'Completed with errors'), ('FAILED', 'Failed')], default='PENDING', max_length=24)),
                ('requested_mode', models.CharField(choices=[('SEQUENTIAL', 'Sequential')], default='SEQUENTIAL', max_length=12)),
                ('configured_max_concurrency', models.PositiveSmallIntegerField(default=1)),
                ('actual_concurrency', models.PositiveSmallIntegerField(default=1)),
                ('question_timeout_seconds', models.PositiveIntegerField()),
                ('inter_question_delay_seconds', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('total_planned', models.PositiveIntegerField()),
                ('selection_filter', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('diagnostic_class', models.CharField(blank=True, max_length=80)),
                ('diagnostic_detail', models.TextField(blank=True)),
                ('launched_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='launched_evaluation_runs', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='catalog.evaluationtarget')),
                ('target_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='catalog.targetrevision')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BuildSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_product_version', models.CharField(blank=True, max_length=120)),
                ('declared_build_id', models.CharField(blank=True, max_length=160)),
                ('declared_git_sha', models.CharField(blank=True, max_length=64)),
                ('runtime_state', models.CharField(choices=[('NOT_ATTEMPTED', 'Not attempted'), ('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('MALFORMED', 'Malformed')], default='NOT_ATTEMPTED', max_length=16)),
                ('runtime_metadata', models.JSONField(blank=True, default=dict)),
                ('runtime_raw_response', models.TextField(blank=True)),
                ('runtime_observed_at', models.DateTimeField(blank=True, null=True)),
                ('runtime_diagnostic', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='build_snapshot', to='evaluations.evaluationrun')),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.PositiveIntegerField()),
                ('question_stable_id', models.CharField(max_length=120)),
                ('question_version_number', models.PositiveIntegerField()),
                ('question_template', models.TextField()),
                ('submitted_question', models.TextField()),
                ('outcome', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('TIMEOUT', 'Timeout')], default='PENDING', max_length=12)),
                ('request_correlation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('adapter_key', models.CharField(max_length=100)),
                ('adapter_version', models.CharField(max_length=80)),
                ('normalizer_key', models.CharField(default='identity-display', max_length=80)),
                ('normalizer_version', models.CharField(default='1', max_length=32)),
                ('raw_request', models.JSONField(blank=True, default=dict)),
                ('protocol_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('raw_response', models.TextField(blank=True)),
                ('raw_answer', models.TextField(blank=True)),
                ('display_answer', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('response_metadata', models.JSONField(blank=True, default=dict)),
                ('target_correlation_id', models.CharField(blank=True, max_length=160)),
                ('error_class', models.CharField(blank=True, max_length=80)),
                ('error_detail', models.TextField(blank=True)),
                ('preflight_error_class', models.CharField(blank=True, max_length=80)),
                ('preflight_error_detail', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('build_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.buildsnapshot')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='catalog.question')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='catalog.questionversion')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='evaluations.evaluationrun')),
                ('target_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.targetrevision')),
            ],
            options={
                'ordering': ('run', 'question_order'),
            },
        ),
        migrations.CreateModel(
            name='ResolvedBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('resolution_mode', models.CharField(choices=[('FIXED_ADMIN', 'Fixed admin')], max_length=24)),
                ('value', models.JSONField()),
                ('display_value', models.TextField()),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolved_bindings', to='evaluations.execution')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TargetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_display_name', models.CharField(max_length=180)),
                ('product_display_name', models.CharField(max_length=160)),
                ('environment_display_name', models.CharField(max_length=160)),
                ('endpoint', models.URLField(max_length=500)),
                ('adapter_key', models.CharField(max_length=100)),
                ('adapter_version', models.CharField(max_length=80)),
                ('credential_reference', models.CharField(blank=True, max_length=128)),
                ('classification', models.CharField(max_length=16)),
                ('supports_runtime_metadata', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='target_snapshot', to='evaluations.evaluationrun')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_snapshots', to='catalog.evaluationtarget')),
                ('target_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_snapshots', to='catalog.targetrevision')),
            ],
        ),
        migrations.AddField(
            model_name='execution',
            name='target_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.targetsnapshot'),
        ),
        migrations.AddConstraint(
            model_name='evaluationrun',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('PENDING', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED'))), name='evaluations_run_state'),
        ),
        migrations.AddConstraint(
            model_name='evaluationrun',
            constraint=models.CheckConstraint(condition=models.Q(('requested_mode', 'SEQUENTIAL')), name='evaluations_m3_sequential_only'),
        ),
        migrations.AddConstraint(
            model_name='evaluationrun',
            constraint=models.CheckConstraint(condition=models.Q(('actual_concurrency', 1)), name='evaluations_m3_actual_concurrency_one'),
        ),
        migrations.AddConstraint(
            model_name='evaluationrun',
            constraint=models.CheckConstraint(condition=models.Q(('total_planned__gte', 1)), name='evaluations_run_nonempty_manifest'),
        ),
        migrations.AddConstraint(
            model_name='buildsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('runtime_state__in', ('NOT_ATTEMPTED', 'AVAILABLE', 'UNAVAILABLE', 'MALFORMED'))), name='evaluations_build_snapshot_runtime_state'),
        ),
        migrations.AddConstraint(
            model_name='resolvedbinding',
            constraint=models.UniqueConstraint(fields=('execution', 'name'), name='evaluations_resolved_binding_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.UniqueConstraint(fields=('run', 'question_order'), name='evaluations_manifest_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ('PENDING', 'RUNNING', 'SUCCESS', 'ERROR', 'TIMEOUT'))), name='evaluations_execution_outcome'),
        ),
    ]
