# Generated by Django 5.2.17 on 2026-09-03 16:26

from django.conf import settings
from django.db import migrations, models


def classify_legacy_running_executions(apps, schema_editor):
    Execution = apps.get_model("evaluations", "Execution")
    Execution.objects.filter(outcome="RUNNING").update(target_call_phase="LEGACY_UNKNOWN")


def unclassify_legacy_running_executions(apps, schema_editor):
    Execution = apps.get_model("evaluations", "Execution")
    Execution.objects.filter(outcome="RUNNING", target_call_phase="LEGACY_UNKNOWN").update(
        target_call_phase="NONE"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_m3_durable_execution'),
        ('evaluations', '0001_m3_durable_execution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='evaluationrun',
            name='evaluations_m3_sequential_only',
        ),
        migrations.RemoveConstraint(
            model_name='evaluationrun',
            name='evaluations_m3_actual_concurrency_one',
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='next_dispatch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='claim_attempt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='execution',
            name='claim_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='claim_lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='claim_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='claim_worker_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='execution',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='target_call_phase',
            field=models.CharField(choices=[('NONE', 'No active claim'), ('CLAIMED', 'Claimed before target submission'), ('SUBMISSION_STARTED', 'Target submission may have occurred'), ('TERMINAL', 'Terminal observation persisted'), ('LEGACY_UNKNOWN', 'Legacy interrupted work')], default='NONE', max_length=24),
        ),
        migrations.RunPython(classify_legacy_running_executions, unclassify_legacy_running_executions),
        migrations.AlterField(
            model_name='evaluationrun',
            name='requested_mode',
            field=models.CharField(choices=[('SEQUENTIAL', 'Sequential'), ('PARALLEL', 'Parallel')], default='SEQUENTIAL', max_length=12),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['outcome', 'target_revision', 'claim_lease_expires_at'], name='eval_exec_claim_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['run', 'outcome', 'question_order'], name='eval_exec_run_claim_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationrun',
            constraint=models.CheckConstraint(condition=models.Q(('requested_mode__in', ('SEQUENTIAL', 'PARALLEL'))), name='evaluations_run_execution_mode'),
        ),
        migrations.AddConstraint(
            model_name='evaluationrun',
            constraint=models.CheckConstraint(condition=models.Q(('configured_max_concurrency__gte', 1), ('actual_concurrency__gte', 1), ('actual_concurrency__lte', models.F('configured_max_concurrency'))), name='evaluations_run_concurrency_bounds'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('claim_heartbeat_at__isnull', True), ('claim_lease_expires_at__isnull', True), ('claim_token__isnull', True), ('claim_worker_id', ''), ('claimed_at__isnull', True), ('outcome', 'PENDING'), ('target_call_phase', 'NONE')), models.Q(('claim_heartbeat_at__isnull', False), ('claim_lease_expires_at__isnull', False), ('claim_token__isnull', False), ('claimed_at__isnull', False), ('outcome', 'RUNNING'), ('target_call_phase__in', ('CLAIMED', 'SUBMISSION_STARTED')), models.Q(('claim_worker_id', ''), _negated=True)), models.Q(('claim_token__isnull', True), ('claim_worker_id', ''), ('outcome', 'RUNNING'), ('target_call_phase__in', ('NONE', 'LEGACY_UNKNOWN'))), models.Q(('outcome__in', ('SUCCESS', 'ERROR', 'TIMEOUT')), ('target_call_phase__in', ('NONE', 'TERMINAL'))), _connector='OR'), name='evaluations_execution_claim_state'),
        ),
    ]
