# Generated by Django 5.2.17 on 2026-09-03 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_m3_durable_execution'),
        ('evaluations', '0002_remove_evaluationrun_evaluations_m3_sequential_only_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMJudgeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('model_identifier', models.CharField(max_length=160)),
                ('judge_version', models.CharField(max_length=80)),
                ('prompt_version', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('COMPLETE', 'Complete'), ('ERROR', 'Error')], max_length=12)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReviewTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('NONE', 'None'), ('REQUIRED', 'Required'), ('REVIEWED', 'Reviewed')], max_length=12)),
                ('cause', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='retry_request_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='source_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retry_runs', to='evaluations.execution'),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='source_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rerun_runs', to='evaluations.evaluationrun'),
        ),
        migrations.AddField(
            model_name='execution',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='invalidated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invalidated_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='execution',
            name='review_state',
            field=models.CharField(choices=[('NONE', 'None'), ('REQUIRED', 'Required'), ('REVIEWED', 'Reviewed')], default='NONE', max_length=12),
        ),
        migrations.AddField(
            model_name='execution',
            name='source_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retried_executions', to='evaluations.execution'),
        ),
        migrations.AddField(
            model_name='execution',
            name='validity',
            field=models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid')], default='VALID', max_length=8),
        ),
        migrations.CreateModel(
            name='AutomatedEvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_key', models.CharField(max_length=100)),
                ('evaluator_version', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('COMPLETE', 'Complete'), ('ERROR', 'Error')], max_length=12)),
                ('outcome', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('CANNOT_CONCLUDE', 'Cannot conclude')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automated_results', to='evaluations.execution')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stewardbench_comments', to=settings.AUTH_USER_MODEL)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='evaluations.execution')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='evaluations.evaluationrun')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExecutionValidityDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity', models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid')], max_length=8)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validity_decisions', to='evaluations.comment')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_validity_decisions', to=settings.AUTH_USER_MODEL)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validity_history', to='evaluations.execution')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='evaluations.executionvaliditydecision')),
            ],
            options={
                'ordering': ('decided_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HumanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgment', models.CharField(choices=[('GOOD', 'Good'), ('BAD', 'Bad')], max_length=4)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_events', to='evaluations.comment')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_history', to='evaluations.execution')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='human_reviews', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='evaluations.humanreview')),
            ],
            options={
                'ordering': ('reviewed_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='execution',
            name='current_human_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_executions', to='evaluations.humanreview'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.CheckConstraint(condition=models.Q(('review_state__in', ('NONE', 'REQUIRED', 'REVIEWED'))), name='evaluations_execution_review_state'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.CheckConstraint(condition=models.Q(('validity__in', ('VALID', 'INVALID'))), name='evaluations_execution_validity'),
        ),
        migrations.AddField(
            model_name='llmjudgeresult',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='llm_judge_results', to='evaluations.execution'),
        ),
        migrations.AddField(
            model_name='reviewtracking',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_tracking_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewtracking',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_tracking_events', to='evaluations.execution'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('execution__isnull', True), ('run__isnull', False)), models.Q(('execution__isnull', False), ('run__isnull', True)), _connector='OR'), name='evaluations_comment_one_parent'),
        ),
    ]
