# Generated by Django 5.2.17 on 2026-09-03 18:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_m3_durable_execution'),
        ('evaluations', '0003_llmjudgeresult_reviewtracking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='baseline_execution',
            field=models.ForeignKey(blank=True, help_text='Historical baseline observation whose exact inputs this controlled replay uses.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controlled_replay_executions', to='evaluations.execution'),
        ),
        migrations.AddField(
            model_name='execution',
            name='comparison_non_comparable_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='resolvedbinding',
            name='resolution_mode',
            field=models.CharField(choices=[('FIXED_ADMIN', 'Fixed admin'), ('BASELINE_FROZEN', 'Baseline frozen')], max_length=24),
        ),
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_attention', models.BooleanField(default=False)),
                ('attention_opened_at', models.DateTimeField(blank=True, null=True)),
                ('attention_detail', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_baselines', to=settings.AUTH_USER_MODEL)),
                ('source_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promoted_baselines', to='evaluations.evaluationrun')),
                ('source_target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baselines', to='catalog.evaluationtarget')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='comparison_baseline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controlled_runs', to='evaluations.baseline'),
        ),
        migrations.CreateModel(
            name='BaselineAttentionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baseline_attention_events', to=settings.AUTH_USER_MODEL)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attention_events', to='evaluations.baseline')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baseline_attention_events', to='evaluations.execution')),
                ('validity_decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baseline_attention_events', to='evaluations.executionvaliditydecision')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BaselineMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='evaluations.baseline')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baseline_memberships', to='evaluations.execution')),
            ],
            options={
                'ordering': ('execution__question_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BaselineStateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baseline_state_events', to=settings.AUTH_USER_MODEL)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_history', to='evaluations.baseline')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_key', models.CharField(default='exact', max_length=80)),
                ('algorithm_version', models.CharField(default='exact-v1', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparisons', to='evaluations.baseline')),
                ('current_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comparison', to='evaluations.evaluationrun')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ComparisonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_state', models.CharField(choices=[('UNCHANGED', 'Unchanged'), ('CHANGED', 'Changed'), ('NON_COMPARABLE', 'Non-comparable')], max_length=20)),
                ('exact_equal', models.BooleanField(blank=True, null=True)),
                ('baseline_normalized_hash', models.CharField(blank=True, max_length=64)),
                ('current_normalized_hash', models.CharField(blank=True, max_length=64)),
                ('non_comparable_reason', models.CharField(blank=True, max_length=120)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baseline_execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baseline_comparison_items', to='evaluations.execution')),
                ('baseline_human_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baseline_comparison_item_snapshots', to='evaluations.humanreview')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='evaluations.comparison')),
                ('current_execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_comparison_items', to='evaluations.execution')),
                ('current_human_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_comparison_item_snapshots', to='evaluations.humanreview')),
            ],
            options={
                'ordering': ('current_execution__question_order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='baseline',
            constraint=models.UniqueConstraint(fields=('source_target', 'name'), name='evaluations_baseline_name_per_target_unique'),
        ),
        migrations.AddConstraint(
            model_name='baselineattentionevent',
            constraint=models.UniqueConstraint(fields=('baseline', 'execution'), name='evaluations_baseline_attention_member_unique'),
        ),
        migrations.AddConstraint(
            model_name='baselinemembership',
            constraint=models.UniqueConstraint(fields=('baseline', 'execution'), name='evaluations_baseline_membership_unique'),
        ),
        migrations.AddConstraint(
            model_name='comparison',
            constraint=models.UniqueConstraint(fields=('baseline', 'current_run'), name='evaluations_comparison_baseline_run_unique'),
        ),
        migrations.AddConstraint(
            model_name='comparisonitem',
            constraint=models.UniqueConstraint(fields=('comparison', 'current_execution'), name='evaluations_comparison_item_current_unique'),
        ),
        migrations.AddConstraint(
            model_name='comparisonitem',
            constraint=models.CheckConstraint(condition=models.Q(('change_state__in', ('UNCHANGED', 'CHANGED', 'NON_COMPARABLE'))), name='evaluations_comparison_item_change_state'),
        ),
    ]
