# Generated by Django 5.2.17 on 2026-09-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0004_m6_baselines_exact_comparison"),
    ]

    operations = [
        migrations.CreateModel(
            name="SemanticComparisonResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("EQUIVALENT", "Equivalent"),
                            ("MATERIAL_CHANGE", "Material change"),
                            ("UNCERTAIN", "Uncertain"),
                            ("ERROR", "Comparator error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider_key", models.CharField(max_length=100)),
                ("model_identifier", models.CharField(max_length=160)),
                ("comparator_version", models.CharField(max_length=80)),
                ("prompt_version", models.CharField(blank=True, max_length=80)),
                ("input_fingerprint", models.CharField(max_length=64)),
                ("input_manifest", models.JSONField(blank=True, default=dict)),
                ("rationale", models.TextField(blank=True)),
                ("error_class", models.CharField(blank=True, max_length=100)),
                ("error_detail", models.TextField(blank=True)),
                ("raw_result", models.JSONField(blank=True, default=dict)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comparison_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="semantic_results",
                        to="evaluations.comparisonitem",
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="evaluations.semanticcomparisonresult",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["comparison_item", "-created_at"],
                        name="eval_semantic_current_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("outcome__in", ("EQUIVALENT", "MATERIAL_CHANGE", "UNCERTAIN", "ERROR"))),
                        name="evaluations_semantic_result_outcome",
                    )
                ],
            },
        ),
    ]
