# Generated by Django 5.2.17 on 2026-09-03 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_m8_conversation_scenarios'),
        ('evaluations', '0005_semanticcomparisonresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='conversation_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='catalog.conversationturn'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='catalog.question'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='question_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='catalog.questionversion'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='question_version_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ConversationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_session_id', models.CharField(blank=True, max_length=200)),
                ('session_metadata', models.JSONField(blank=True, default=dict)),
                ('session_state', models.CharField(choices=[('PENDING', 'Pending session'), ('ACTIVE', 'Active'), ('UNUSABLE', 'Session unusable'), ('CLOSED', 'Closed')], default='PENDING', max_length=12)),
                ('session_diagnostic', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('baseline_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controlled_replay_attempts', to='evaluations.conversationattempt')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_attempt', to='evaluations.evaluationrun')),
                ('scenario_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='catalog.conversationscenarioversion')),
                ('source_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retry_attempts', to='evaluations.conversationattempt')),
            ],
            options={
                'ordering': ('-run__created_at',),
            },
        ),
        migrations.AddField(
            model_name='execution',
            name='conversation_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turn_executions', to='evaluations.conversationattempt'),
        ),
        migrations.AddConstraint(
            model_name='execution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('conversation_attempt__isnull', True), ('conversation_turn__isnull', True), ('question__isnull', False), ('question_version__isnull', False)), models.Q(('conversation_attempt__isnull', False), ('conversation_turn__isnull', False)), _connector='OR'), name='evaluations_execution_question_or_conversation_turn'),
        ),
        migrations.AddConstraint(
            model_name='conversationattempt',
            constraint=models.CheckConstraint(condition=models.Q(('session_state__in', ('PENDING', 'ACTIVE', 'UNUSABLE', 'CLOSED'))), name='evaluations_conversation_session_state'),
        ),
    ]
