# Generated by Django 5.2.17 on 2026-09-03 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_m8_conversation_scenarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedevaluationresult',
            name='configuration_version',
            field=models.CharField(default='legacy-m5', max_length=80),
        ),
        migrations.AddField(
            model_name='automatedevaluationresult',
            name='error_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='automatedevaluationresult',
            name='input_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='automatedevaluationresult',
            name='input_manifest',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='automatedevaluationresult',
            name='latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatedevaluationresult',
            name='mechanism',
            field=models.CharField(choices=[('DETERMINISTIC', 'Deterministic'), ('POLICY', 'Policy'), ('EXPECTED_CANNOT_CONCLUDE', 'Expected cannot conclude')], default='DETERMINISTIC', max_length=32),
        ),
        migrations.AddField(
            model_name='automatedevaluationresult',
            name='raw_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='automatedevaluationresult',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='evaluations.automatedevaluationresult'),
        ),
        migrations.AddField(
            model_name='llmjudgeresult',
            name='advisory_disposition',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='llmjudgeresult',
            name='error_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='llmjudgeresult',
            name='input_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='llmjudgeresult',
            name='input_manifest',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='llmjudgeresult',
            name='latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmjudgeresult',
            name='provider_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='llmjudgeresult',
            name='rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='llmjudgeresult',
            name='raw_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='llmjudgeresult',
            name='rubric_id',
            field=models.CharField(default='legacy-unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='llmjudgeresult',
            name='rubric_version',
            field=models.CharField(default='legacy-m5', max_length=80),
        ),
        migrations.AddField(
            model_name='llmjudgeresult',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='evaluations.llmjudgeresult'),
        ),
        migrations.AlterField(
            model_name='automatedevaluationresult',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Complete'), ('NOT_APPLICABLE', 'Not applicable'), ('ERROR', 'Error')], max_length=16),
        ),
        migrations.CreateModel(
            name='EvaluationInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EVALUATOR', 'Evaluator'), ('JUDGE', 'LLM judge')], max_length=16)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('evaluator_key', models.CharField(max_length=100)),
                ('evaluator_version', models.CharField(max_length=80)),
                ('mechanism', models.CharField(blank=True, max_length=32)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('model_identifier', models.CharField(blank=True, max_length=160)),
                ('judge_version', models.CharField(blank=True, max_length=80)),
                ('rubric_id', models.CharField(blank=True, max_length=100)),
                ('rubric_version', models.CharField(blank=True, max_length=80)),
                ('prompt_version', models.CharField(blank=True, max_length=80)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('input_fingerprint', models.CharField(blank=True, max_length=64)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('worker_id', models.CharField(blank=True, max_length=200)),
                ('claim_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('result_error_class', models.CharField(blank=True, max_length=100)),
                ('result_error_detail', models.TextField(blank=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_invocations', to='evaluations.execution')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_evaluation_invocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='automatedevaluationresult',
            name='invocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automated_results', to='evaluations.evaluationinvocation'),
        ),
        migrations.AddField(
            model_name='llmjudgeresult',
            name='invocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='judge_results', to='evaluations.evaluationinvocation'),
        ),
        migrations.AddIndex(
            model_name='evaluationinvocation',
            index=models.Index(fields=['state', 'kind', 'id'], name='eval_invocation_claim_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationinvocation',
            index=models.Index(fields=['execution', 'kind', 'id'], name='eval_invocation_current_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationinvocation',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('EVALUATOR', 'JUDGE'))), name='evaluations_invocation_kind'),
        ),
        migrations.AddConstraint(
            model_name='evaluationinvocation',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED'))), name='evaluations_invocation_state'),
        ),
    ]
