# Generated by Django 5.2.17 on 2026-09-03 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_m9_evaluators_and_judge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationinvocation',
            name='claim_attempt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluationinvocation',
            name='claim_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationinvocation',
            name='claim_lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='evaluationinvocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('claim_heartbeat_at__isnull', True), ('claim_lease_expires_at__isnull', True), ('claim_token__isnull', True), ('state', 'PENDING'), ('worker_id', '')), models.Q(('claim_heartbeat_at__isnull', False), ('claim_lease_expires_at__isnull', False), ('claim_token__isnull', False), ('state', 'RUNNING'), models.Q(('worker_id', ''), _negated=True)), ('state__in', ('COMPLETED', 'FAILED')), _connector='OR'), name='evaluations_invocation_claim_state'),
        ),
    ]
