# Generated by Django 5.2.17 on 2026-09-04

from django.db import migrations, models


def classify_existing_latency(apps, schema_editor):
    Execution = apps.get_model("evaluations", "Execution")
    for execution in Execution.objects.filter(outcome="SUCCESS", latency_ms__isnull=False).iterator():
        latency = execution.latency_ms
        execution.performance_classification = (
            "TARGET" if latency <= 1000 else "GOOD" if latency <= 2000 else "ACCEPTABLE"
            if latency <= 5000 else "SLOW" if latency <= 10000 else "BAD"
        )
        execution.save(update_fields=("performance_classification",))


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0008_m9_evaluator_invocation_recovery"),
    ]

    operations = [
        migrations.AddField(model_name="execution", name="input_tokens", field=models.PositiveIntegerField(blank=True, null=True)),
        migrations.AddField(model_name="execution", name="output_tokens", field=models.PositiveIntegerField(blank=True, null=True)),
        migrations.AddField(model_name="execution", name="total_tokens", field=models.PositiveIntegerField(blank=True, null=True)),
        migrations.AddField(model_name="execution", name="token_usage_metadata", field=models.JSONField(blank=True, default=dict)),
        migrations.AddField(model_name="execution", name="runtime_telemetry", field=models.JSONField(blank=True, default=dict)),
        migrations.AddField(model_name="execution", name="internal_timing_metadata", field=models.JSONField(blank=True, default=dict)),
        migrations.AddField(model_name="execution", name="performance_policy_version", field=models.CharField(default="opss-performance-v1", max_length=80)),
        migrations.AddField(model_name="execution", name="performance_classification", field=models.CharField(blank=True, max_length=16)),
        migrations.AddField(model_name="comparisonitem", name="performance_policy_version", field=models.CharField(default="opss-performance-v1", max_length=80)),
        migrations.AddField(model_name="comparisonitem", name="baseline_latency_ms", field=models.PositiveIntegerField(blank=True, null=True)),
        migrations.AddField(model_name="comparisonitem", name="current_latency_ms", field=models.PositiveIntegerField(blank=True, null=True)),
        migrations.AddField(model_name="comparisonitem", name="latency_delta_ms", field=models.IntegerField(blank=True, null=True)),
        migrations.AddField(model_name="comparisonitem", name="latency_delta_percent", field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.AddField(model_name="comparisonitem", name="baseline_performance_classification", field=models.CharField(blank=True, max_length=16)),
        migrations.AddField(model_name="comparisonitem", name="current_performance_classification", field=models.CharField(blank=True, max_length=16)),
        migrations.AddField(model_name="comparisonitem", name="performance_change", field=models.CharField(blank=True, max_length=16)),
        migrations.AddField(model_name="comparisonitem", name="performance_band_degraded", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="comparisonitem", name="input_token_delta", field=models.IntegerField(blank=True, null=True)),
        migrations.AddField(model_name="comparisonitem", name="output_token_delta", field=models.IntegerField(blank=True, null=True)),
        migrations.AddField(model_name="comparisonitem", name="total_token_delta", field=models.IntegerField(blank=True, null=True)),
        migrations.AddField(model_name="comparisonitem", name="input_token_delta_percent", field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.AddField(model_name="comparisonitem", name="output_token_delta_percent", field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.AddField(model_name="comparisonitem", name="total_token_delta_percent", field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.RunPython(classify_existing_latency, migrations.RunPython.noop),
    ]
