# Generated by Django 5.2.17 on 2026-09-03 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_identifier', models.CharField(max_length=100)),
                ('mapping_name', models.CharField(max_length=160)),
                ('mapping_version', models.PositiveIntegerField()),
                ('importer_version', models.CharField(max_length=40)),
                ('source_filename', models.CharField(max_length=255)),
                ('source_sha256', models.CharField(max_length=64)),
                ('source_size_bytes', models.PositiveBigIntegerField()),
                ('source_metadata', models.JSONField(default=dict)),
                ('workbook_inventory', models.JSONField(default=dict)),
                ('mapping_snapshot', models.JSONField(default=dict)),
                ('reconciliation_counts', models.JSONField(default=dict)),
                ('imported_at', models.DateTimeField()),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-imported_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='ImportWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=80)),
                ('source_rows', models.JSONField(default=list)),
                ('code', models.CharField(choices=[('AMBIGUOUS_CANONICAL_LINK', 'Ambiguous canonical link'), ('POTENTIAL_BINDING_REQUIRES_REVIEW', 'Potential binding requires review'), ('CONVERSATION_GROUPING_DEFERRED', 'Conversation grouping deferred'), ('LEGACY_METADATA_UNKNOWN', 'Legacy metadata unknown'), ('UNSUPPORTED_SOURCE_FIELD', 'Unsupported source field'), ('SOURCE_CONFLICT', 'Source conflict')], max_length=48)),
                ('explanation', models.TextField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warnings', to='corpus.legacyimportbatch')),
            ],
            options={
                'ordering': ('sheet_name', 'source_rows', 'code', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ImportedSourceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=80)),
                ('source_row_number', models.PositiveIntegerField()),
                ('source_role', models.CharField(choices=[('TARGET_QUESTIONS', 'Target questions'), ('RANDOM_GENERALIZATION', 'Random generalization'), ('KB_RAG', 'Knowledge base / RAG'), ('KNOWN_QUESTIONS', 'Known questions')], max_length=32)),
                ('classification', models.CharField(choices=[('QUESTION_DEFINITION', 'Question definition'), ('LEGACY_OBSERVATION', 'Legacy observation'), ('QUESTION_AND_OBSERVATION', 'Question and legacy observation'), ('STRUCTURAL', 'Structural')], max_length=32)),
                ('interpretation_source', models.CharField(choices=[('SOURCE_DATA', 'Source data'), ('PRODUCT_OWNER_MAPPING', 'Product-owner mapping'), ('STRUCTURAL', 'Structural')], default='SOURCE_DATA', max_length=32)),
                ('structural_kind', models.CharField(blank=True, max_length=40)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('mapping_context', models.JSONField(default=dict)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imported_source_rows', to='catalog.domain')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imported_source_rows', to='catalog.question')),
                ('question_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imported_source_rows', to='catalog.questionversion')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_rows', to='corpus.legacyimportbatch')),
            ],
            options={
                'ordering': ('sheet_name', 'source_row_number'),
            },
        ),
        migrations.CreateModel(
            name='LegacyObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_question_text', models.TextField()),
                ('observed_answer_text', models.TextField(blank=True, null=True)),
                ('answer_fidelity', models.CharField(choices=[('SOURCE_TEXT_UNKNOWN_EXACTNESS', 'Source text of unknown exactness')], max_length=48)),
                ('legacy_expectation', models.TextField(blank=True, null=True)),
                ('expected_answer_role', models.CharField(choices=[('LEGACY_EXPECTATION', 'Legacy expectation')], max_length=40)),
                ('acceptable_source_value', models.TextField(blank=True, null=True)),
                ('legacy_judgment', models.CharField(blank=True, choices=[('GOOD', 'Good'), ('BAD', 'Bad')], max_length=8, null=True)),
                ('judgment_source', models.CharField(choices=[('IMPORTED_LEGACY', 'Imported legacy')], max_length=32)),
                ('comments', models.TextField(blank=True, null=True)),
                ('secondary_comments', models.TextField(blank=True, null=True)),
                ('experiment_metadata', models.JSONField(default=dict)),
                ('unknown_metadata', models.JSONField(default=list)),
                ('imported_at', models.DateTimeField()),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_observations', to='catalog.question')),
                ('question_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_observations', to='catalog.questionversion')),
                ('source_row', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_observation', to='corpus.importedsourcerow')),
            ],
            options={
                'ordering': ('source_row__sheet_name', 'source_row__source_row_number'),
            },
        ),
        migrations.CreateModel(
            name='ImportedSourceCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.CharField(max_length=20)),
                ('column_name', models.CharField(blank=True, max_length=80)),
                ('data_type', models.CharField(blank=True, max_length=20)),
                ('raw_value', models.TextField(blank=True, null=True)),
                ('displayed_value', models.TextField(blank=True, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('source_row', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_cells', to='corpus.importedsourcerow')),
            ],
            options={
                'ordering': ('source_row_id', 'coordinate'),
                'constraints': [models.UniqueConstraint(fields=('source_row', 'coordinate'), name='corpus_source_cell_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='legacyimportbatch',
            constraint=models.UniqueConstraint(fields=('mapping_identifier', 'mapping_version', 'source_sha256'), name='corpus_batch_source_mapping_unique'),
        ),
        migrations.AddConstraint(
            model_name='legacyimportbatch',
            constraint=models.CheckConstraint(condition=models.Q(('source_sha256__regex', '^[0-9a-f]{64}$')), name='corpus_batch_sha256_format'),
        ),
        migrations.AddConstraint(
            model_name='legacyimportbatch',
            constraint=models.CheckConstraint(condition=models.Q(('mapping_version__gte', 1)), name='corpus_batch_mapping_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='importwarning',
            constraint=models.CheckConstraint(condition=models.Q(('code__in', ('AMBIGUOUS_CANONICAL_LINK', 'POTENTIAL_BINDING_REQUIRES_REVIEW', 'CONVERSATION_GROUPING_DEFERRED', 'LEGACY_METADATA_UNKNOWN', 'UNSUPPORTED_SOURCE_FIELD', 'SOURCE_CONFLICT'))), name='corpus_import_warning_code'),
        ),
        migrations.AddConstraint(
            model_name='importedsourcerow',
            constraint=models.UniqueConstraint(fields=('batch', 'sheet_name', 'source_row_number'), name='corpus_source_row_unique'),
        ),
        migrations.AddConstraint(
            model_name='importedsourcerow',
            constraint=models.CheckConstraint(condition=models.Q(('classification__in', ('QUESTION_DEFINITION', 'LEGACY_OBSERVATION', 'QUESTION_AND_OBSERVATION', 'STRUCTURAL'))), name='corpus_source_row_classification'),
        ),
        migrations.AddConstraint(
            model_name='importedsourcerow',
            constraint=models.CheckConstraint(condition=models.Q(('interpretation_source__in', ('SOURCE_DATA', 'PRODUCT_OWNER_MAPPING', 'STRUCTURAL'))), name='corpus_source_row_interpretation'),
        ),
        migrations.AddConstraint(
            model_name='importedsourcerow',
            constraint=models.CheckConstraint(condition=models.Q(('source_role__in', ('TARGET_QUESTIONS', 'RANDOM_GENERALIZATION', 'KB_RAG', 'KNOWN_QUESTIONS'))), name='corpus_source_row_role'),
        ),
        migrations.AddConstraint(
            model_name='importedsourcerow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('question__isnull', True), ('question_version__isnull', True)), models.Q(('question__isnull', False), ('question_version__isnull', False)), _connector='OR'), name='corpus_source_row_question_version_pair'),
        ),
        migrations.AddConstraint(
            model_name='importedsourcerow',
            constraint=models.CheckConstraint(condition=models.Q(('source_row_number__gte', 1)), name='corpus_source_row_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='legacyobservation',
            constraint=models.CheckConstraint(condition=models.Q(('legacy_judgment__isnull', True), ('legacy_judgment__in', ('GOOD', 'BAD')), _connector='OR'), name='corpus_legacy_judgment'),
        ),
        migrations.AddConstraint(
            model_name='legacyobservation',
            constraint=models.CheckConstraint(condition=models.Q(('answer_fidelity', 'SOURCE_TEXT_UNKNOWN_EXACTNESS')), name='corpus_legacy_answer_fidelity'),
        ),
        migrations.AddConstraint(
            model_name='legacyobservation',
            constraint=models.CheckConstraint(condition=models.Q(('expected_answer_role', 'LEGACY_EXPECTATION')), name='corpus_legacy_expectation_role'),
        ),
        migrations.AddConstraint(
            model_name='legacyobservation',
            constraint=models.CheckConstraint(condition=models.Q(('judgment_source', 'IMPORTED_LEGACY')), name='corpus_legacy_judgment_source'),
        ),
    ]
