# Generated by Django 5.2.17 on 2026-09-03 12:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_catalog_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('display_name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_catalog_environments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('display_name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_catalog_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='EvaluationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=180, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='catalog.environment')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_catalog_targets', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='catalog.product')),
            ],
            options={
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stable_id', models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, dots, underscores, and hyphens only.', regex='^[A-Za-z0-9][A-Za-z0-9._-]*$')])),
                ('kind', models.CharField(choices=[('SINGLE_TURN', 'Single turn'), ('CONVERSATION', 'Conversation')], default='SINGLE_TURN', max_length=16)),
                ('lifecycle', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=8)),
                ('rationale', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='catalog.domain')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_catalog_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('stable_id',),
            },
        ),
        migrations.CreateModel(
            name='QuestionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('version_number', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('evaluation_guidance', models.TextField(blank=True)),
                ('change_type', models.CharField(blank=True, choices=[('PRODUCT_REQUIREMENT_CHANGE', 'Product requirement change'), ('TEST_BUG_FIX', 'Test bug fix'), ('GROUND_TRUTH_UPDATE', 'Ground truth update'), ('DATA_MODEL_EVOLUTION', 'Data model evolution')], max_length=32)),
                ('change_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='catalog.question')),
            ],
            options={
                'ordering': ('-version_number',),
            },
        ),
        migrations.CreateModel(
            name='BindingDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, dots, underscores, and hyphens only.', regex='^[A-Za-z0-9][A-Za-z0-9._-]*$')])),
                ('value_type', models.CharField(choices=[('TEXT', 'Text'), ('IDENTIFIER', 'Identifier'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('TIMESTAMP', 'Timestamp')], max_length=16)),
                ('is_required', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='binding_definitions', to='catalog.questionversion')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='catalog.tag'),
        ),
        migrations.CreateModel(
            name='HistoricalFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stable_id', models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, dots, underscores, and hyphens only.', regex='^[A-Za-z0-9][A-Za-z0-9._-]*$')])),
                ('name', models.CharField(max_length=180)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('fixed_parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_fixtures', to='catalog.environment')),
                ('tags', models.ManyToManyField(blank=True, related_name='historical_fixtures', to='catalog.tag')),
            ],
            options={
                'ordering': ('-window_start', 'stable_id'),
            },
        ),
        migrations.CreateModel(
            name='TargetRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('endpoint', models.URLField(max_length=500)),
                ('adapter_key', models.CharField(max_length=100)),
                ('adapter_version', models.CharField(max_length=80)),
                ('credential_reference', models.CharField(blank=True, help_text='Symbolic deployment-secret reference only; never enter a credential value.', max_length=128, validators=[django.core.validators.RegexValidator(message='Use a symbolic external reference, not credential material.', regex='^[A-Za-z0-9][A-Za-z0-9._/-]*$')])),
                ('classification', models.CharField(choices=[('PRODUCTION', 'Production'), ('DEVELOPMENT', 'Development'), ('STAGING', 'Staging'), ('LAB_TEST', 'Lab/test'), ('EXTERNAL', 'External')], max_length=16)),
                ('supports_question_api', models.BooleanField(default=True)),
                ('supports_conversation_session', models.BooleanField(default=False)),
                ('supports_runtime_metadata', models.BooleanField(default=False)),
                ('supports_health_check', models.BooleanField(default=False)),
                ('default_execution_mode', models.CharField(choices=[('SEQUENTIAL', 'Sequential'), ('PARALLEL', 'Parallel')], default='SEQUENTIAL', max_length=12)),
                ('max_concurrency', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64)])),
                ('question_timeout_seconds', models.PositiveIntegerField(default=120, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(86400)])),
                ('inter_question_delay_seconds', models.DecimalField(decimal_places=3, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3600)])),
                ('declared_product_version', models.CharField(blank=True, max_length=120)),
                ('declared_build_id', models.CharField(blank=True, max_length=160)),
                ('declared_git_sha', models.CharField(blank=True, max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='catalog.evaluationtarget')),
            ],
            options={
                'ordering': ('-revision_number',),
            },
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.UniqueConstraint(fields=('question', 'version_number'), name='catalog_question_version_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('question',), name='catalog_question_one_current_version'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='catalog_question_version_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.CheckConstraint(condition=models.Q(('change_type', ''), ('change_type__in', ('PRODUCT_REQUIREMENT_CHANGE', 'TEST_BUG_FIX', 'GROUND_TRUTH_UPDATE', 'DATA_MODEL_EVOLUTION')), _connector='OR'), name='catalog_question_version_change_type'),
        ),
        migrations.AddConstraint(
            model_name='bindingdefinition',
            constraint=models.UniqueConstraint(fields=('question_version', 'name'), name='catalog_binding_name_per_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='bindingdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('value_type__in', ('TEXT', 'IDENTIFIER', 'INTEGER', 'DECIMAL', 'TIMESTAMP'))), name='catalog_binding_value_type'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('SINGLE_TURN', 'CONVERSATION'))), name='catalog_question_kind'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('lifecycle__in', ('DRAFT', 'ACTIVE', 'RETIRED'))), name='catalog_question_lifecycle'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lifecycle', 'ACTIVE'), _negated=True), ('domain__isnull', False), _connector='OR'), name='catalog_active_question_has_domain'),
        ),
        migrations.AddConstraint(
            model_name='historicalfixture',
            constraint=models.CheckConstraint(condition=models.Q(('window_end__gt', models.F('window_start'))), name='catalog_fixture_valid_window'),
        ),
        migrations.AddConstraint(
            model_name='targetrevision',
            constraint=models.UniqueConstraint(fields=('target', 'revision_number'), name='catalog_target_revision_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='targetrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('target',), name='catalog_target_one_current_revision'),
        ),
        migrations.AddConstraint(
            model_name='targetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='catalog_target_revision_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='targetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('classification__in', ('PRODUCTION', 'DEVELOPMENT', 'STAGING', 'LAB_TEST', 'EXTERNAL'))), name='catalog_target_revision_classification'),
        ),
        migrations.AddConstraint(
            model_name='targetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('default_execution_mode__in', ('SEQUENTIAL', 'PARALLEL'))), name='catalog_target_revision_mode'),
        ),
        migrations.AddConstraint(
            model_name='targetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('max_concurrency__gte', 1), ('max_concurrency__lte', 64)), name='catalog_target_revision_concurrency'),
        ),
        migrations.AddConstraint(
            model_name='targetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('question_timeout_seconds__gte', 1), ('question_timeout_seconds__lte', 86400)), name='catalog_target_revision_timeout'),
        ),
        migrations.AddConstraint(
            model_name='targetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('inter_question_delay_seconds__gte', 0), ('inter_question_delay_seconds__lte', 3600)), name='catalog_target_revision_delay'),
        ),
    ]
