# Generated by Django 5.2.17 on 2026-09-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindingdefinition',
            name='fixed_value',
            field=models.JSONField(blank=True, help_text='Optional non-secret M3 fixed/admin value. It is substituted only for the exact {{binding_name}} placeholder.', null=True),
        ),
    ]
