# Generated by Django 5.2.17 on 2026-09-03 20:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_m3_durable_execution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stable_id', models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, dots, underscores, and hyphens only.', regex='^[A-Za-z0-9][A-Za-z0-9._-]*$')])),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('lifecycle', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversation_scenarios', to='catalog.domain')),
                ('question', models.OneToOneField(help_text='Stable CONVERSATION Question companion; ScenarioVersion owns executable turns.', on_delete=django.db.models.deletion.PROTECT, related_name='conversation_scenario', to='catalog.question')),
                ('tags', models.ManyToManyField(blank=True, related_name='conversation_scenarios', to='catalog.tag')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_catalog_conversation_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('stable_id',),
            },
        ),
        migrations.CreateModel(
            name='ConversationScenarioVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('version_number', models.PositiveIntegerField()),
                ('definition', models.TextField(blank=True)),
                ('expected_session_behavior', models.CharField(default='shared-session-required', max_length=160)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='catalog.conversationscenario')),
                ('scenario_question_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_scenario_version', to='catalog.questionversion')),
            ],
            options={
                'ordering': ('-version_number',),
            },
        ),
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('stable_turn_id', models.CharField(max_length=160, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, dots, underscores, and hyphens only.', regex='^[A-Za-z0-9][A-Za-z0-9._-]*$')])),
                ('prompt_template', models.TextField()),
                ('static_bindings', models.JSONField(blank=True, default=dict)),
                ('required_for_overall', models.BooleanField(default=True)),
                ('source_sheet', models.CharField(blank=True, max_length=120)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversation_turns', to='catalog.question')),
                ('canonical_question_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversation_turns', to='catalog.questionversion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_catalog_conversation_turns', to=settings.AUTH_USER_MODEL)),
                ('scenario_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turns', to='catalog.conversationscenarioversion')),
            ],
            options={
                'ordering': ('scenario_version', 'ordinal'),
            },
        ),
        migrations.AddConstraint(
            model_name='conversationscenario',
            constraint=models.CheckConstraint(condition=models.Q(('lifecycle__in', ('DRAFT', 'ACTIVE', 'RETIRED'))), name='catalog_conversation_scenario_lifecycle'),
        ),
        migrations.AddConstraint(
            model_name='conversationscenario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lifecycle', 'ACTIVE'), _negated=True), ('domain__isnull', False), _connector='OR'), name='catalog_active_scenario_has_domain'),
        ),
        migrations.AddConstraint(
            model_name='conversationscenarioversion',
            constraint=models.UniqueConstraint(fields=('scenario', 'version_number'), name='catalog_conversation_version_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='conversationscenarioversion',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('scenario',), name='catalog_conversation_one_current_version'),
        ),
        migrations.AddConstraint(
            model_name='conversationscenarioversion',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='catalog_conversation_version_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='conversationturn',
            constraint=models.UniqueConstraint(fields=('scenario_version', 'ordinal'), name='catalog_conversation_turn_ordinal_unique'),
        ),
        migrations.AddConstraint(
            model_name='conversationturn',
            constraint=models.UniqueConstraint(fields=('scenario_version', 'stable_turn_id'), name='catalog_conversation_turn_stable_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='conversationturn',
            constraint=models.CheckConstraint(condition=models.Q(('ordinal__gte', 1)), name='catalog_conversation_turn_positive_ordinal'),
        ),
    ]
